pool:
  vmImage: 'ubuntu-16.04'
variables:
  CHROMEDRIVER_VERSION: LATEST
  NODE_ENV: production
  NODE_OPTIONS: --max-old-space-size=8000
  NPM_TAG: latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
