pool:
  vmImage: 'ubuntu-16.04'
variables:
  CHROMEDRIVER_VERSION: LATEST
  NODE_OPTIONS: --max-old-space-size=8000
  NPM_TAG: latest
  JEST_JUNIT_OUTPUT_NAME: results.xml
  JEST_JUNIT_OUTPUT_DIR: test-results/unit

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: ci
- task: Npm@1
  displayName: 'npm run test:lint'
  inputs:
    command: custom
    customCommand: run test:lint -- --quiet --output-file test-results/eslint/results.xml --format junit
- task: Npm@1
  displayName: 'npm run test:unit'
  inputs:
    command: custom
    customCommand: run test:unit -- --reporters="default" --reporters="jest-junit" --coverage --coverageReporters=text --coverageReporters=lcov
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: run build
- task: Npm@1
  displayName: 'npm run test:integration'
  inputs:
    command: custom
    customCommand: run test:integration
- task: PublishTestResults@2
  inputs:
    testResultsFiles: test-results/**/results.xml
- task: CopyFiles@2
  inputs:
    contents: build/**
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: build
- task: CopyFiles@2
  inputs:
    contents: dist/**
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: dist
