pool:
  vmImage: 'ubuntu-16.04'
variables:
  CHROMEDRIVER_VERSION: LATEST
  NODE_OPTIONS: --max-old-space-size=8000
  NPM_TAG: latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: ci
- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    customCommand: test
